export const GRADOVI_SRBIJE = [
    'Ada', 'Aleksandrovac', 'Aleksinac', 'Apatin', 'Arilje',
    'Bač', 'Bačka Palanka', 'Bačka Topola', 'Bajina Bašta', 'Batočina',
    'Bela Crkva', 'Bela Palanka', 'Beograd', 'Blace', 'Bogatić',
    'Bojnik', 'Boljevac', 'Bor', 'Bosilegrad', 'Brus',
    'Bujanovac', 'Valjevo', 'Varvarin', 'Velika Plana', 'Veliko Gradište',
    'Vladičin Han', 'Vladimirci', 'Vlasotince', 'Vranje', 'Vrbas',
    'Vrnjačka Banja', 'Vršac', 'Gadžin Han', 'Golubac', 'Gornji Milanovac',
    'Despotovac', 'Dimitrovgrad', 'Doljevac', 'Žabalj', 'Žabari',
    'Žagubica', 'Žitorađa', 'Zaječar', 'Zrenjanin', 'Ivanjica',
    'Inđija', 'Irig', 'Jagodina', 'Kanjiža', 'Kikinda',
    'Kladovo', 'Knić', 'Knjaževac', 'Kovačica', 'Kovin',
    'Kosjerić', 'Kragujevac', 'Kraljevo', 'Krupanj', 'Kruševac',
    'Kučevo', 'Kula', 'Lajkovac', 'Lapovo', 'Lebane',
    'Leskovac', 'Loznica', 'Lučani', 'Ljig', 'Ljubovija',
    'Majdanpek', 'Malo Crniće', 'Medveđa', 'Merošina', 'Mionica',
    'Negotin', 'Niš', 'Nova Crnja', 'Nova Varoš', 'Novi Bečej',
    'Novi Kneževac', 'Novi Pazar', 'Novi Sad', 'Odžaci', 'Opovo',
    'Osečina', 'Paraćin', 'Pećinci', 'Petrovac na Mlavi', 'Pirot',
    'Plandište', 'Požarevac', 'Požega', 'Preševo', 'Priboj',
    'Prijepolje', 'Prokuplje', 'Rača', 'Raška', 'Ražanj',
    'Rekovac', 'Ruma', 'Svilajnac', 'Sečanj', 'Senta',
    'Sjenica', 'Smederevo', 'Smederevska Palanka', 'Sokobanja', 'Sombor',
    'Srbobran', 'Sremska Mitrovica', 'Sremski Karlovci', 'Stara Pazova', 'Surdulica',
    'Subotica', 'Temerin', 'Titel', 'Topola', 'Trgovište',
    'Trstenik', 'Tutin', 'Ćićevac', 'Ćuprija', 'Ub',
    'Užice', 'Čajetina', 'Čačak', 'Čoka', 'Šabac',
    'Šid',
  ];